### ISSUE TITLE
Port the interpreter to JavaScript

### ISSUE THREAD

**Issue by pigworker** [msp-strath/Mary#6]
The rock bottom way to get our code running client-side is to port the interpreter to JavaScript and then render parsed code as whatever our JS representation of terms might be.

It's not clear how much mechanical assistance we can get with this port (which we have to keep in sync with the Haskell version), but at the moment, it's not such a big job.

**Comment by pigworker** [comment]
This is well under way. I haven't done the prims yet.

**Comment by gallais** [comment]
I have tried to refactor & extend the current implementation like so but when I
try to run the test suite, the js backend seems to hang on `primitives.shonkier`.

```js
    function primNumBin(nm,implem,cs) {
        if (hasLength(cs) && cs.length == 2) {
            if (cs[0].tag == "Value" && cs[1].tag == "Value" &&
                cs[0].value.tag == "Lit" && cs[1].value.tag == "Lit") {
                var x = cs[0].value.literal;
                var y = cs[1].value.literal;
                if (!stringy(x) && !stringy(y)) {
                    return Use(Lit(LitNum(implem(x,y))));
                };
                return Handle("Invalid_" + nm + "_ArgType",[],null);
            };
            return Handle("Invalid_" + nm + "_ArgRequest",[],null);
        };
        return Handle("Invalid_" + nm + "_Arity",[],null);
    };
    function primNumAdd(cs) {
        return primNumBin("primNumMinus"
                          , function(x,y){ return (x.num*y.den + y.num*x.den,x.den*y.den);}
                          , cs
                         );
    };
    function primNumMult(cs) {
        return primNumBin("primNumMult"
                          , function(x,y){ return (x.num*y.num,x.den*y.den);}
                          , cs
                         );
    };
    function primNumMinus(cs) {
        return primNumBin("primNumMinus"
                          , function(x,y){ return (x.num*y.den - y.num*x.den,x.den*y.den);}
                          , cs
                         );
    };

    switch (f) {
    case "primStringConcat":
        return primStringConcat(vs);
    case "primNumAdd":
        return primNumAdd(vs);
    case "primNumMinus":
        return primNumMinus(vs);
    case "primNumMult":
        return primNumMult(vs);
    default:
        return Handle("NoPrim",[],null);
    };
};
```

**Comment by gallais** [comment]
Additionally, I have found several bugs in the js interpreter: running

```
mary -shonkierjs examples/quick-exit.shonkier | node -
```

I get the following error:

```
[stdin]:65
    return (x.num == y.num && x.den == y.den);
              ^

TypeError: Cannot read property 'num' of undefined
    at LitEq ([stdin]:65:15)
    at vmatch ([stdin]:172:20)
    at cmatch ([stdin]:138:20)
    at cmatches ([stdin]:128:14)
    at shonkier ([stdin]:399:21)
    at [stdin]:463:20
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

And both `bipping` and `reader` seem broken: they evaluate to the `NotFuny`
exception.

**Comment by pigworker** [comment]
am shit at js
